# Generated by Django 5.2.8 on 2025-11-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_original', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('contenido_adaptado', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('failed', 'Fallido'), ('manual', 'Manual Pendiente')], default='draft', max_length=20)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.post')),
            ],
        ),
    ]
