# Generated by Django 5.2.8 on 2025-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='published_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
